(function(e){Number.prototype.map=function(a,b,d,c){return d+(this-a)/(b-a)*(c-d)};Number.prototype.limit=function(a,b){return Math.min(b,Math.max(a,this))};Number.prototype.round=function(a){a=Math.pow(10,a||0);return Math.round(this*a)/a};Number.prototype.floor=function(){return Math.floor(this)};Number.prototype.ceil=function(){return Math.ceil(this)};Number.prototype.toInt=function(){return this|0};Number.prototype.toRad=function(){return this/180*Math.PI};Number.prototype.toDeg=function(){return 180*
this/Math.PI};Object.defineProperty(Array.prototype,"erase",{value:function(a){for(var b=this.length;b--;)this[b]===a&&this.splice(b,1);return this}});Object.defineProperty(Array.prototype,"random",{value:function(a){return this[Math.floor(Math.random()*this.length)]}});Function.prototype.bind=Function.prototype.bind||function(a){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var b=Array.prototype.slice.call(arguments,1),d=this,
c=function(){},e=function(){return d.apply(this instanceof c&&a?this:a,b.concat(Array.prototype.slice.call(arguments)))};c.prototype=this.prototype;e.prototype=new c;return e};e.ig={game:null,debug:null,version:"1.24",global:e,modules:{},resources:[],ready:!1,baked:!1,nocache:"",ua:{},prefix:e.ImpactPrefix||"",lib:"/assets/game/pong/",_current:null,_loadQueue:[],_waitForOnload:0,$:function(a){return"#"==a.charAt(0)?document.getElementById(a.substr(1)):document.getElementsByTagName(a)},$new:function(a){return document.createElement(a)},
copy:function(a){if(!a||"object"!=typeof a||a instanceof HTMLElement||a instanceof ig.Class)return a;if(a instanceof Array)for(var b=[],d=0,c=a.length;d<c;d++)b[d]=ig.copy(a[d]);else for(d in b={},a)b[d]=ig.copy(a[d]);return b},merge:function(a,b){for(var d in b){var c=b[d];"object"!=typeof c||c instanceof HTMLElement||c instanceof ig.Class||null===c?a[d]=c:(a[d]&&"object"==typeof a[d]||(a[d]=c instanceof Array?[]:{}),ig.merge(a[d],c))}return a},ksort:function(a){if(!a||"object"!=typeof a)return[];
var b=[],d=[],c;for(c in a)b.push(c);b.sort();for(c=0;c<b.length;c++)d.push(a[b[c]]);return d},setVendorAttribute:function(a,b,d){var c=b.charAt(0).toUpperCase()+b.substr(1);a[b]=a["ms"+c]=a["moz"+c]=a["webkit"+c]=a["o"+c]=d},getVendorAttribute:function(a,b){var d=b.charAt(0).toUpperCase()+b.substr(1);return a[b]||a["ms"+d]||a["moz"+d]||a["webkit"+d]||a["o"+d]},normalizeVendorAttribute:function(a,b){var d=ig.getVendorAttribute(a,b);!a[b]&&d&&(a[b]=d)},getImagePixels:function(a,b,d,c,e){var g=ig.$new("canvas");
g.width=a.width;g.height=a.height;var k=g.getContext("2d");ig.System.SCALE.CRISP(g,k);var m=ig.getVendorAttribute(k,"backingStorePixelRatio")||1;ig.normalizeVendorAttribute(k,"getImageDataHD");var f=a.width/m,h=a.height/m;g.width=Math.ceil(f);g.height=Math.ceil(h);k.drawImage(a,0,0,f,h);return 1===m?k.getImageData(b,d,c,e):k.getImageDataHD(b,d,c,e)},module:function(a){if(ig._current)throw"Module '"+ig._current.name+"' defines nothing";if(ig.modules[a]&&ig.modules[a].body)throw"Module '"+a+"' is already defined";
ig._current={name:a,requires:[],loaded:!1,body:null};ig.modules[a]=ig._current;ig._loadQueue.push(ig._current);return ig},requires:function(){ig._current.requires=Array.prototype.slice.call(arguments);return ig},defines:function(a){ig._current.body=a;ig._current=null;ig._initDOMReady()},addResource:function(a){ig.resources.push(a)},setNocache:function(a){ig.nocache=a?"?"+Date.now():""},log:function(){},assert:function(a,b){},show:function(a,b){},mark:function(a,b){},_loadScript:function(a,b){ig.modules[a]=
{name:a,requires:[],loaded:!1,body:null};ig._waitForOnload++;var d=ig.prefix+ig.lib+a.replace(/\./g,"/")+".js"+ig.nocache,c=ig.$new("script");c.type="text/javascript";c.src=d;c.onload=function(){ig._waitForOnload--;ig._execModules()};c.onerror=function(){throw"Failed to load module "+a+" at "+d+" required from "+b;};ig.$("head")[0].appendChild(c)},_execModules:function(){for(var a=!1,b=0;b<ig._loadQueue.length;b++){for(var d=ig._loadQueue[b],c=!0,e=0;e<d.requires.length;e++){var g=d.requires[e];ig.modules[g]?
ig.modules[g].loaded||(c=!1):(c=!1,ig._loadScript(g,d.name))}c&&d.body&&(ig._loadQueue.splice(b,1),d.loaded=!0,d.body(),a=!0,b--)}if(a)ig._execModules();else if(!ig.baked&&0==ig._waitForOnload&&0!=ig._loadQueue.length){a=[];for(b=0;b<ig._loadQueue.length;b++){c=[];g=ig._loadQueue[b].requires;for(e=0;e<g.length;e++)(d=ig.modules[g[e]])&&d.loaded||c.push(g[e]);a.push(ig._loadQueue[b].name+" (requires: "+c.join(", ")+")")}throw"Unresolved (or circular?) dependencies. Most likely there's a name/path mismatch for one of the listed modules or a previous syntax error prevents a module from loading:\n"+
a.join("\n");}},_DOMReady:function(){if(!ig.modules["dom.ready"].loaded){if(!document.body)return setTimeout(ig._DOMReady,13);ig.modules["dom.ready"].loaded=!0;ig._waitForOnload--;ig._execModules()}return 0},_boot:function(){document.location.href.match(/\?nocache/)&&ig.setNocache(!0);ig.ua.pixelRatio=e.devicePixelRatio||1;ig.ua.viewport={width:e.innerWidth,height:e.innerHeight};ig.ua.screen={width:e.screen.availWidth*ig.ua.pixelRatio,height:e.screen.availHeight*ig.ua.pixelRatio};ig.ua.iPhone=/iPhone/i.test(navigator.userAgent);
ig.ua.iPhone4=ig.ua.iPhone&&2==ig.ua.pixelRatio;ig.ua.iPad=/iPad/i.test(navigator.userAgent);ig.ua.android=/android/i.test(navigator.userAgent);ig.ua.winPhone=/Windows Phone/i.test(navigator.userAgent);ig.ua.iOS=ig.ua.iPhone||ig.ua.iPad;ig.ua.mobile=ig.ua.iOS||ig.ua.android||ig.ua.winPhone||/mobile/i.test(navigator.userAgent);ig.ua.touchDevice="ontouchstart"in e||e.navigator.msMaxTouchPoints},_initDOMReady:function(){ig.modules["dom.ready"]?ig._execModules():(ig._boot(),ig.modules["dom.ready"]={requires:[],
loaded:!1,body:null},ig._waitForOnload++,"complete"===document.readyState?ig._DOMReady():(document.addEventListener("DOMContentLoaded",ig._DOMReady,!1),e.addEventListener("load",ig._DOMReady,!1)))}};ig.normalizeVendorAttribute(e,"requestAnimationFrame");if(e.requestAnimationFrame){var n=1,f={};e.ig.setAnimation=function(a,b){var d=n++;f[d]=!0;var c=function(){f[d]&&(e.requestAnimationFrame(c,b),a())};e.requestAnimationFrame(c,b);return d};e.ig.clearAnimation=function(a){delete f[a]}}else e.ig.setAnimation=
function(a,b){return e.setInterval(a,1E3/60)},e.ig.clearAnimation=function(a){e.clearInterval(a)};var h=!1,l=/xyz/.test(function(){xyz})?/\bparent\b/:/.*/,p=0;e.ig.Class=function(){};var q=function(a){var b=this.prototype,d={},c;for(c in a)"function"==typeof a[c]&&"function"==typeof b[c]&&l.test(a[c])?(d[c]=b[c],b[c]=function(a,b){return function(){var c=this.parent;this.parent=d[a];var e=b.apply(this,arguments);this.parent=c;return e}}(c,a[c])):b[c]=a[c]};e.ig.Class.extend=function(a){function b(){if(!h){if(this.staticInstantiate){var a=
this.staticInstantiate.apply(this,arguments);if(a)return a}for(var b in this)"object"==typeof this[b]&&(this[b]=ig.copy(this[b]));this.init&&this.init.apply(this,arguments)}return this}var d=this.prototype;h=!0;var c=new this;h=!1;for(var f in a)"function"==typeof a[f]&&"function"==typeof d[f]&&l.test(a[f])?c[f]=function(a,b){return function(){var c=this.parent;this.parent=d[a];var e=b.apply(this,arguments);this.parent=c;return e}}(f,a[f]):c[f]=a[f];b.prototype=c;b.prototype.constructor=b;b.extend=
e.ig.Class.extend;b.inject=q;b.classId=c.classId=++p;return b};e.ImpactMixin&&ig.merge(ig,e.ImpactMixin)})(window);ig.module("impact.impact").requires("dom.ready","impact.loader","impact.system","impact.input","impact.sound").defines(function(){ig.main=function(e,n,f,h,l,p,q){ig.system=new ig.System(e,f,h,l,p||1);ig.input=new ig.Input;ig.soundManager=new ig.SoundManager;ig.music=new ig.Music;ig.ready=!0;(new (q||ig.Loader)(n,ig.resources)).load()}});ig.module("main").requires("impact.game","impact.font","entities.puck","entities.paddle-cpu","entities.paddle-player","levels.main").defines(function(){MyGame=ig.Game.extend({font:new ig.Font("/assets/game/pong/media/04b03.font.png"),init:function(){ig.input.bind(ig.KEY.UP_ARROW,"up");ig.input.bind(ig.KEY.DOWN_ARROW,"down");this.loadLevel(LevelMain)},update:function(){this.parent()},draw:function(){this.parent();this.font.draw("It Works!",ig.system.width/2,ig.system.height/2,ig.Font.ALIGN.CENTER)}});
ig.main("#canvas",MyGame,60,768,480,1)});
